### ISSUE TITLE
Change track-finder labelling 

### ISSUE THREAD

**Issue by jlingema** [dinyar/uGMTfirmware#225]
Hi,
To avoid confusion (especially for newcomers), I suggest to change the labels containing "forward" to "endcap" (for LUTs etc.) to be consistent with written documents and the "global CMS naming".

**Comment by dinyar** [comment]
This will require changes in software too. Will write a ticket there.

**Comment by dinyar** [comment]
This also needs to be tested thoroughly before merging back to master. However the changes in software mentioned above will be needed to be able to run the testbench.
