### ISSUE TITLE
Add possibility to disable bottom/top part of track-finders

### ISSUE THREAD

**Issue by dinyar** [dinyar/uGMTfirmware#329]
For cosmic running it is convenient to deactivate the inputs of the track-finders for the top of the detector. This should be done in uGMT.

**Comment by dinyar** [comment]
It's probably most flexible if individual links can be deactivated, e.g. using one register per track finder (and one bit per channel).

This probably needs to go into the event setup though -- I'm not sure how much word this would be. (@thomreis?)

**Comment by thomreis** [comment]
We will have to add this to the ES parameters which will not make people happy I guess.
But then it should be fairly straight forward.

**Comment by dinyar** [comment]
This still needs to be tested, but is otherwise done.

**Comment by dinyar** [comment]
This doesn't seem to work fully in hardware yet..
