### ISSUE TITLE
Change winning precedence after tie in inter-TF cancel-out

### ISSUE THREAD

**Issue by dinyar** [dinyar/uGMTfirmware#333]
Currently if e.g. muons from BMTF1 are compared to muons from BMTF2 in the COU the muons in BMTF2 will 'win' (i.e. not be cancelled) in case of a draw. This should be inverted.

**Comment by dinyar** [comment]
This might interest @thomreis too. I'm not sure how it's done in the emulator currently.

**Comment by thomreis** [comment]
In the emulator also the 2nd will win.
