### ISSUE TITLE
Increase default readout window

### ISSUE THREAD

**Issue by dinyar** [dinyar/uGMTfirmware#346]
With the switch to the 10g DAQ link we could send a significantly larger payload to DAQ. For this reason it might be useful to send (at least) +/-1 BX for the unprescaled readout.

Things to do to make this work:
- [x] Modify uGMT configuration in database
- [x] Request stress test from cDAQ

@thomreis Will this require changes in the unpacker or emulator?

**Comment by dinyar** [comment]
This has been changed online and validated in a global stress test.

**Comment by dinyar** [comment]
I forgot: @thomreis, will this automatically be picked up by the unpacker? (I assume yes, but just to make sure.)

**Comment by thomreis** [comment]
Yes, the unpacker will know how to handle the larger window.
