### ISSUE TITLE
Increase cancel-out LUT size for B/OMTF

### ISSUE THREAD

**Issue by dinyar** [dinyar/uGMTfirmware#347]
The current LUTs for the matching of ghosts allow a maximum dEta value of 0.162. In the case of the overlap region between BMTF and OMTF dEta for the cancel-out window should be larger.

The LUT should therefore be increased in size by one bit.

**Comment by dinyar** [comment]
Going to try to increase the LUT size for all LUTs for the moment.

**Comment by dinyar** [comment]
This can be synthesised without problems. The LUTs for the coordinate-based cancel-out now expect 5 bits of eta instead of formerly 4 bits. @thomreis, if it's ok for you I would try to integrate my changes to the emulator with your help on Monday and then we could try to increase the LUT size in the emulator too?

**Comment by thomreis** [comment]
Yes, this can be done.

**Comment by thomreis** [comment]
Included in PR https://github.com/cms-l1t-offline/cmssw/pull/246

**Comment by dinyar** [comment]
This was tested and will be deployed in the next release.
