### ISSUE TITLE
Increase range of phi extrapolation

### ISSUE THREAD

**Issue by dinyar** [dinyar/uGMTfirmware#369]
Following studies done on the invariant mass resolution of muons with extrapolated coordinates the following changes should be implemented:

- [x] Increase output of phi extrapolation LUT by 1 bit and shift this value by 1 bit less than before (3->2)
- [x] Use 7 bit of the pT value at the input and only 5 bit of the eta value (instead of 6 bit of each value)

**Comment by thomreis** [comment]
It should be only 5 bit of the eta value. total input bits stay at 12.

**Comment by dinyar** [comment]
Ah right, that was a typo in the comment :) Thanks for pointing it out!

**Comment by dinyar** [comment]
Apparently I forgot to implement the second bullet point. Still need to change the inputs of the extrapolation LUTs.

**Comment by dinyar** [comment]
Tests pass, this seems to work.
