### ISSUE TITLE
Valid bit synchronisation

### ISSUE THREAD

**Issue by jlingema** [dinyar/uGMTfirmware#88]
As seen in the patterns to be found in [1], the valid bit stays 1 for one BX too long. Maybe we should directly move to an implementation where the valid bit goes to 1 and stays there until one orbit is over?

[1] https://twiki.cern.ch/twiki/pub/Sandbox/JoschkaLingemannUGMTFirmware/ugmt_v0_2_12_buffer_dumps.tgz

**Comment by dinyar** [comment]
@jlingema just to follow up (and given the number of changes that have been done since the bug appeared): is this still the case?
